### PR TITLE
Nearest Neighbour algorithm - 1st Part

### LINKED ISSUE #11: Nearest Neighbour Algorithm (1º Fase)

### PR DESCRIPTION
**Pull request by monkin77**
Closes #14 
Basic implementation of the NN algorithm.
While doing it I realized we should have a way to access a client in O(1) through a Vertex. I thought about storing the clients in a map on the Bakery class (vertexID as key for example). However there is something I would like to clarify, can we have 2 clients on the same vertex? If so, should we use a map with multiples values for a certain key?

### CODE REVIEW

**Review by itsdomsantos — COMMENTED** [review]
How can we have 2 clients in the same vertex?

**Comment by monkin77** [comment]
> How can we have 2 clients in the same vertex?

It depends on the input file. Since the vertices are read from a file (Right now the Grid 4x4 file) and the coordinates are given by (latitude, longitude), I don't know if we can have in the Bakery input file more than 1 client with the same (Latitude, Longitude). If we do, then we need to associate them to the same vertex. To do this, we could use a map with multiples values for a certain key, 
or make each vertex store the clients that have that certain position.

**Review by BrunoRosendo — CHANGES_REQUESTED** [review]
Looks good. I just think we should indeed have a client pointer stored in the vertex to check if there's a client living there. And I don't think we should have multiple clients in the same vertex

**Comment by BrunoRosendo** [comment]
So, besides moving some folders, I changed the following in the NN algorithm:

- I created a new Dijkstra, which stops onde we reach all the vertices in a given vector. This is meant to be the clients' houses
- In the NN algorithm, I use this new dijkstra when we're calculation the distance from the current vertex to the remaining clients, we don't need to reach all the vertices we don't care about

I didn't test the running times but this should help the efficiency of the algorithm

**Comment by itsdomsantos** [comment]
> So, besides moving some folders, I changed the following in the NN algorithm:
> 
> * I created a new Dijkstra, which stops onde we reach all the vertices in a given vector. This is meant to be the clients' houses
> * In the NN algorithm, I use this new dijkstra when we're calculation the distance from the current vertex to the remaining clients, we don't need to reach all the vertices we don't care about
> 
> I didn't test the running times but this should help the efficiency of the algorithm

OkOk sounds great. I also agree that we should have client pointers, which makes our code more efficient.

**Review by BrunoRosendo — APPROVED** [review]
I think it looks good

**Pull request merged**
